module.exports = {
  // arrowParens: "always",
  // bracketSpacing: true,
  // embeddedLanguageFormatting: "auto",
  // endOfLine: "lf",
  // htmlWhitespaceSensitivity: "css",
  // insertPragma: false,
  // jsxBracketSameLine: false,
  // jsxSingleQuote: false,
  printWidth: 100,
  proseWrap: 'always',
  // quoteProps: "as-needed",
  // rangeStart: 0,
  // requirePragma: false,
  // semi: true,
  singleQuote: true,
  // tabWidth: 2,
  trailingComma: 'all',
  // useTabs: false,
};
